routes/auth.py
from flask import Blueprint, request, render_template, redirect, url_for, session
from services.auth_service import get_email, create_user, authenticate_user
import re

auth_bp = Blueprint('auth', __name__)

# EMAIL VALIDATION
def is_valid_email(email):
    regex = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    return re.match(regex, email)

# SIGN UP
@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    error = None
    if request.method == 'POST':
        name = request.form['name'].strip()
        email = request.form['email'].strip()
        password = request.form['password']
        confirm_password = request.form['confirm_password']

        if not name or not email or not password or not confirm_password:
            error = "Please fill out all fields."
        elif not is_valid_email(email):
            error = "Invalid email format."
        elif password != confirm_password:
            error = "Passwords do not match!"
        elif len(password) < 6:
            error = "Password must be at least 6 characters."
        elif get_email(email) is not None:
            error = "Email already registered!"
        else:
            success, message = create_user(name, email, password)
            if success:
                return redirect(url_for('auth.signin'))
            else:
                error = f"Error: {message}"

    return render_template('signup.jinja', error=error)


# SIGN IN
@auth_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    error = None
    if request.method == 'POST':
        email = request.form['email'].strip()
        password = request.form['password']

        success, result = authenticate_user(email, password)

        if success:
            account = result
            session['user_id'] = account['id']
            session['user_name'] = account['name']
            session['user_role'] = account['role']
            session['user_email'] = account['email']

            return redirect(url_for('dashboard.dashboard'))
        else:
            error = result

    return render_template('signin.jinja', error=error)

# LOGOUT
@auth_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.signin'))

routes/dashboard.py
from flask import Blueprint, render_template, session
from utils import skills_str_to_comma, datetime_to_str, is_expired
from services.job_post_service import get_active_jobs

dashboard_bp = Blueprint('dashboard', __name__)

# DASHBOARD
@dashboard_bp.route('/')
def dashboard():
    jobs = get_active_jobs()
    for i in range(len(jobs)):
        jobs[i]['skills'] = skills_str_to_comma(jobs[i]['skills'])
        jobs[i]['is_expired'] = is_expired(jobs[i]['deadline'])
        jobs[i]['deadline'] = datetime_to_str(jobs[i]['deadline'])

    return render_template(
        'dashboard.jinja',
        jobs=jobs,
        user_name=session.get('user_name'),
        user_email=session.get('user_email'),
        user_role = session.get('user_role'),
        active_page='dashboard'
    )

routes/jobs.py
from services.job_post_service import get_job_post, insert_job_post, delete_job_by_id, get_job_applications, already_applied
from services.resume_service import get_resume
from flask import Blueprint, render_template, request, session, redirect, url_for, jsonify, flash
from utils import skills_str_to_list, datetime_to_str, load_json, is_expired

jobs_bp = Blueprint('jobs', __name__)

# POST JOB
@jobs_bp.route('/post-job', methods=['GET', 'POST'])
def post_job():
    if 'user_id' not in session or session.get('user_role') != 'recruiter':
        return redirect(url_for('auth.signin'))

    if request.method == 'POST':
        job_title = request.form['job_title']
        experience = int(request.form['experience'])
        education = request.form['education']
        skills = request.form['skills']
        location = request.form['location']
        deadline = request.form['deadline']
        user_id = session['user_id']
        auto_reject = True if request.form['autoReject'] == "TRUE" else False

        success, message = insert_job_post(job_title, experience, education, skills, location, deadline, auto_reject, user_id)
        if success:
            flash(message, "success")
            return redirect(url_for('dashboard.dashboard'))
        else:
            flash(f"Error: {message}", "error")
            return redirect(request.url)

    return render_template(
        'postjob.jinja', 
        user_name=session.get('user_name'),
        user_email=session.get('user_email'),
        user_role = session.get('user_role')
    )

# JOB DETAIL
@jobs_bp.route("/job-detail/<int:job_id>/")
def job_detail(job_id):
    job = get_job_post(job_id)

    if not job:
        return "Job not found", 404
    
    apply_success, can_apply = already_applied(session.get('user_id'), job_id)
    if apply_success:
        job['can_apply'] = can_apply
    else:
        return "Internal Server Error", 500

    job['skills'] = skills_str_to_list(job['skills'])
    job['is_expired'] = is_expired(job['deadline'])
    job['deadline'] = datetime_to_str(job['deadline'])

    role = session.get('user_role')
    success, applications = get_job_applications(job_id)
    if success and applications:
        for i in range(len(applications)):
            res_success, resume = get_resume(applications[i]['resume_id'])
            if res_success:
                applications[i]['name'] = resume['name_res']
                applications[i]['email'] = resume['email_res']
                applications[i]['designation'] = load_json(resume['designation'])
        applications = applications if role == 'recruiter' else None
    else:
        applications = None

    return render_template(
        "jobdetail.jinja",
        job=job,
        applications=applications,
        user_name=session.get('user_name'),
        user_email=session.get('user_email'),
        user_role = session.get('user_role')
    )

# DELETE JOB
@jobs_bp.route('/delete-job/<int:job_id>', methods=['DELETE'])
def delete_job(job_id):
    if 'user_id' not in session or session.get('user_role') != 'recruiter':
        return redirect(url_for('auth.signin'))

    success, message = delete_job_by_id(job_id)
    if not success:
        return jsonify({'error': message}), 404

    flash(message, 'success')
    return jsonify({'message': message}), 200

routes/resume.py
import os
import uuid
from utils import skills_str_to_list, format_explanation, load_json, create_unique_list
from machine_learning import run_system
from services.job_post_service import get_job_post, get_application, already_applied
from services.resume_service import insert_resume, insert_application, check_drive_link, get_resume, update_application
from flask import Blueprint, request, redirect, url_for, flash, session, render_template, current_app, jsonify
from werkzeug.utils import secure_filename

resume_bp = Blueprint('resume', __name__)
ALLOWED_EXTENSIONS = {'pdf'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# UPLOAD RESUME
@resume_bp.route("/job-detail/<int:job_id>/upload-resume", methods=['GET', 'POST'])
def upload_resume(job_id):
    if 'user_id' not in session or session.get('user_role') != 'candidate':
        return redirect(url_for('auth.signin'))
    

    job = get_job_post(job_id)

    job_desc = {
        "Required Designation": job['job_title'],
        "Required Skills": skills_str_to_list(job['skills']),
        "Required Degree": job['education'],
        "Required Years of Experience": job['experience']
    }

    if 'user_id' not in session:
        return redirect(url_for('auth.signin'))
    user_id = session['user_id']

    success_apply, can_apply = already_applied(user_id, job_id)
    if success_apply:
        if not can_apply:
            return redirect(url_for('dashboard.dashboard'))

    if request.method == 'POST':
        file = request.files.get('resumeUpload')
        gdrive = request.form['gdriveLink'].strip()

        is_accessible, message = check_drive_link(gdrive)
        link = None
        if gdrive:
            if is_accessible:
                link = gdrive
            else:
                flash(message, 'error')

        if not file or file.filename == '':
            flash('No file selected.', 'error')
            return redirect(request.url)
        
        if file.content_length > current_app.config['MAX_CONTENT_LENGTH']:
            flash('File too large.', 'error')
            return redirect(request.url)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            ext = os.path.splitext(filename)[1]
            unique_filename = f"{uuid.uuid4().hex}{ext}"
            filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], unique_filename).replace("\\", "/")
            file.save(filepath)

            # Analyze Resume
            success, result = run_system(
                pdf_path=filepath,
                job_desc=job_desc
            )

            if success:
                resume_success, res_id = insert_resume(
                    res_info=result['Resume Information'],
                    filepath=filepath,
                    filename=filename,
                    user_id=user_id,
                    name=session['user_name'],
                    email=session['user_email']
                )

                if not resume_success:
                    return jsonify({'error': res_id}), 500
                
                status = "In Progress"
                if job['is_auto_reject']:
                    if result['Resume Classification'] == "Not Suitable":
                        status = "Rejected"
                
                application_success, application_result = insert_application(
                    res_id=res_id,
                    job_id=job_id,
                    user_id=user_id,
                    gdrive=link,
                    score=result['Score'],
                    recommendation=result['Resume Classification'],
                    explanation=result['Summary'],
                    status=status
                )

                if not application_success:
                    return jsonify({'error': application_result}), 500

                flash(f'File "{filename}" uploaded successfully!', 'success')
                return redirect(url_for('dashboard.dashboard'))
            else:
                flash("Internal Server Error", 'error')
                return redirect(url_for('dashboard.dashboard'))
        else:
            flash('File type not allowed', 'error')
            return redirect(request.url)

    return render_template(
        "upload_resume.jinja",
        job = job,
        user_name=session.get('user_name'),
        user_email=session.get('user_email'),
        user_role=session.get('user_role')
    )

# VIEW RESUME
@resume_bp.route("/resume/<int:application_id>")
def view_resume(application_id):
    if 'user_id' not in session or session.get('user_role') != 'recruiter':
        return redirect(url_for('auth.signin'))
    
    candidate = {}
    application_success, application = get_application(application_id)
    if application_success:
        candidate['application_id'] = application_id
        candidate['score'] = application['score']
        candidate['recommendation'] = application['recommendation']
        candidate['summary'] = format_explanation(application['explanation'])
        candidate['gdrive'] = application['gdrive']

        res_id = application['resume_id']
        resume_success, res = get_resume(res_id)
    
        if resume_success:
            years_exp = load_json(res['years_exp'])
            res_designation = load_json(res['designation'])
            combined = [d for d in years_exp if d.get('designation')]
            combined += [{'exp_range': "-", 'designation': des} for des in res_designation]

            seen = set()
            unique_exp = []
            for item in combined:
                key = item['designation'].lower()  # case-insensitive check
                if key not in seen:
                    seen.add(key)
                    unique_exp.append(item)

            skills = load_json(res['jobskills']) + load_json(res['techtools'])

            candidate['name'] = res['name_res']
            candidate['email'] = res['email_res']
            candidate['filepath'] = res['file_path'].replace('static/', "")
            candidate['skills'] = create_unique_list(skills)
            candidate['softskills'] = create_unique_list(load_json(res['softskill']))
            candidate['education'] = load_json(res['degree'])
            candidate['experience'] = unique_exp
            candidate['companies'] = load_json(res['companies'])
            candidate['college'] = load_json(res['college'])
            candidate['graduation'] = load_json(res['graduation'])

    return render_template(
    "view_resume.jinja",
    user_name=session.get('user_name'),
    user_email=session.get('user_email'),
    user_role=session.get('user_role'),
    candidate=candidate,
)

# UPDATE STATUS
@resume_bp.route("/update-status/<int:application_id>", methods=['POST'])
def update_status(application_id):
    if 'user_id' not in session or session.get('user_role') != 'recruiter':
        return redirect(url_for('auth.signin'))
    
    new_status = request.json.get('status')
    if new_status not in ['Rejected', 'In Progress', 'Proceed']:
        return jsonify({'error': 'Invalid status'}), 400
    
    success, message = update_application(application_id, new_status)
    print(message)
    if not success:
        return jsonify({'error': message}), 404

    flash(message, 'success')
    return jsonify({'message': message}), 200

routes/user.py
from flask import Blueprint, request, session, jsonify, redirect, url_for, render_template, flash
from services.user_service import get_user, edit_profile, get_user_applications
from utils import datetime_to_str

user_bp = Blueprint('user', __name__)

# GET USER NAME
@user_bp.route('/get-user-info', methods=['GET'])
def get_user_info():
    if 'user_id' not in session:
        return jsonify({'error': 'Not logged in'}), 401

    user_id = session['user_id']
    success, user = get_user(user_id)

    if not success:
        return jsonify({'error': "User Not Found"}), 404

    return jsonify({
        'name': user['name'],
        'email': user['email']
    })

# EDIT PROFILE
@user_bp.route('/update-name', methods=['POST'])
def update_name():
    if 'user_id' not in session:
        return jsonify({'error': 'Unauthorized'}), 401
    
    new_name = request.form.get('name', '').strip()
    if not new_name:
        return jsonify({'error': 'Name cannot be empty'}), 400

    user_id = session['user_id']
    success, message = edit_profile(user_id, new_name)
    if not success:
        return jsonify({'error': message}), 500
    session['user_name'] = new_name
    return jsonify({'message': 'Name updated successfully', 'new_name': new_name})


# APPLICATION HISTORY
@user_bp.route('/applications')
def application_history():
    if 'user_id' not in session or session.get('user_role') != 'candidate':
        return redirect(url_for('auth.signin'))
    
    user_id = session.get('user_id')
    success, applications = get_user_applications(user_id)

    if not success:
        return jsonify({'error': applications}), 404
    
    for app in applications:
        app['application_date'] = datetime_to_str(app['application_date'])

    return render_template(
    "application.jinja",
    applications=applications,
    user_name=session.get('user_name'),
    user_email=session.get('user_email'),
    user_role=session.get('user_role'),
    active_page='applications'
)

templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Jobbers{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <div class="logo">Jobbers</div>
        <div class="menu">
            <a href="{{ url_for('dashboard.dashboard') }}" class="btn-nav {% if active_page == 'dashboard' %}active{% endif %}">🏠 Dashboard</a>
            {% if user_role == "candidate" %}
                <a href="{{ url_for('user.application_history') }}" class="btn-nav {% if active_page == 'applications' %}active{% endif %}">📄 My Application</a>
            {% endif %}
            
            {% if user_role %}
                <span class="btn-nav user-icon" id="userIcon" data-bs-toggle="modal" data-bs-target="#userModal">👤 {{ user_name }}</span>
            {%else%}
                <a href="{{ url_for('auth.signin') }}" class="btn-nav signin">Sign In</a>
                <a href="{{ url_for('auth.signup') }}" class="btn-nav signup">Sign Up</a>
            {% endif %}
        </div>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <div id="userModal" class="modal fade">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content">
                <div class="modal-header" style="background-color: #001f4d;">
                    <h3 class="modal-title w-100 text-center m-0" style="color: white;">Profile</h3>
                    <button type="button" class="btn-close white-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="background-color: #f0f0f0;">
                    {% if user_role == "candidate" %}
                        <form id="editNameForm" method="POST" action="{{ url_for('user.update_name') }}">
                            <input type="hidden" name="user_id" value="{{ user_id }}">
                            <label for="name">Username</label>
                            <input type="text" id="name" name="name" value="{{ user_name }}" required>
                            <label for="email">Email</label>
                            <input type="text" id="email" name="email" value="{{ user_email }}" disabled>
                            <div class="modal-footer p-0 d-flex justify-content-between align-items-center">
                                <a href="{{ url_for('auth.logout') }}" class="logout-btn">Log Out</a>
                                <button type="submit" class="save-btn">Save</button>
                            </div>
                        </form>
                    {% elif user_role == "recruiter" %}
                        <form id="editNameForm">
                            <input type="hidden" name="user_id" value="{{ user_id }}">
                            <label for="name">Username</label>
                            <input type="text" id="name" name="name" value="{{ user_name }}" disabled>
                            <label for="email">Email</label>
                            <input type="text" id="email" name="email" value="{{ user_email }}" disabled>
                            <div class="modal-footer pb-0" style="justify-content: center;">
                                <a href="{{ url_for('auth.logout') }}" class="logout-btn">Log Out</a>
                            </div>
                        </form>
                    {% endif %}
                    <div id="successMessage">Saved Succesfully!</div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const name = document.getElementById('name');
        const email = document.getElementById('email');
        const userIcon = document.getElementById('userIcon');
        const successMessage = document.getElementById('successMessage');

        userIcon.addEventListener('click', () => {
            fetch('/get-user-info')
            .then(res => res.json())
            .then(data => {
            if (data.error) {
                alert(data.error);
            } else {
                name.value = data.name;
                email.value = data.email;
            }
            })
            .catch(err => {
            alert("Failed to load user info");
            console.error(err);
            });
        });

        document.getElementById('editNameForm').addEventListener('submit', function (e) {
            e.preventDefault();
            const form = e.target;
            const formData = new FormData(form);

            fetch(form.action, {
                method: 'POST',
                body: formData,
                credentials: 'same-origin'
            })
            .then(response => response.json())
            .then(data => {
                if (data.error) {
                    alert('Error: ' + data.error);
                } else {
                    document.querySelector('.user-icon').textContent = '👤 ' + data.new_name;

                    successMessage.style.display = 'block';

                    setTimeout(() => {
                        successMessage.style.display = 'none';
                        const modal = bootstrap.Modal.getOrCreateInstance(document.getElementById('userModal'));
                        modal.hide();
                    }, 3000);
                }
            })
            .catch(err => {
                alert('Error Occured: ' + err);
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    {% block extra_js %}{% endblock %}
</body>
</html>

templates/base_pelamar.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Jobbers - Pelamar{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base_pelamar.css') }}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <div class="logo">Jobbers</div>
        <div class="menu">
            <a href="{{ url_for('dashboard.dashboard_pelamar') }}" class="btn-nav {% if active_page == 'dashboard' %}active{% endif %}">🏠 Dashboard</a>
            <a href="{{ url_for('user.application_history') }}" class="btn-nav {% if active_page == 'applications' %}active{% endif %}">📄 My Application</a>
            <span class="btn-nav user-icon" id="userIcon">👤 {{ user_name }}</span>
        </div>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <div id="userModal" class="modal">
        <div class="modal-content">
            <span class="close-btn" id="closeModal">&times;</span>

            <div class="modal-header">
                <h2>Profile</h2>
            </div>

            <div class="modal-body">
                <form id="editNameForm" method="POST" action="{{ url_for('user.update_name') }}">
                    <input type="hidden" name="user_id" value="{{ user_id }}">

                    <label for="name">Username</label>
                    <input type="text" id="name" name="name" value="{{ user_name }}" required>

                    <label for="email">Email</label>
                    <input type="text" id="email" name="email" value="{{ user_email }}" disabled>

                    <div class="modal-footer">
                        <button type="submit" class="save-btn">Save</button>
                        <a href="{{ url_for('auth.logout') }}" class="logout-btn">Log Out</a>
                    </div>
                </form>

                <div id="successMessage">Saved Succesfully!</div>
            </div>
        </div>
    </div>

    <script>
        const modal = document.getElementById('userModal');
        const userIcon = document.getElementById('userIcon');
        const closeBtn = document.getElementById('closeModal');
        const successMessage = document.getElementById('successMessage');

        userIcon.addEventListener('click', () => {
            modal.classList.add('show');
        });

        closeBtn.addEventListener('click', () => {
            modal.classList.remove('show');
            successMessage.style.display = 'none';
        });

        window.addEventListener('click', (e) => {
            if (e.target === modal) {
                modal.classList.remove('show');
                successMessage.style.display = 'none';
            }
        });

        document.getElementById('editNameForm').addEventListener('submit', function (e) {
            e.preventDefault();
            const form = e.target;
            const formData = new FormData(form);

            fetch(form.action, {
                method: 'POST',
                body: formData,
                credentials: 'same-origin'
            })
            .then(response => response.json())
            .then(data => {
                if (data.error) {
                    alert('Error: ' + data.error);
                } else {
                    document.querySelector('.user-icon').textContent = '👤 ' + data.new_name;

                    successMessage.style.display = 'block';

                    setTimeout(() => {
                        successMessage.style.display = 'none';
                        modal.classList.remove('show');
                    }, 2000);
                }
            })
            .catch(err => {
                alert('Error Occured: ' + err);
            });
        });
    </script>

    {% block extra_js %}{% endblock %}
</body>
</html>

templates/dashboard.jinja
{% extends "base.jinja" %}

{% block title %}Dashboard{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
{% endblock %}

{% block content %}
  {% if user_role == "recruiter" %}
    <a href="/post-job" class="post-job-btn">+ Post New Job</a>
  {% endif %}
  <h1>Find Your <span class="highlight">Dream Job</span> Today!</h1>
  {% if user_name %}
    <p class='welcome-text'>Welcome Back, {{ user_name }}!</p>
  {%endif%}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <div class="flash-messages">
        {% for category, message in messages %}
          <div class="flash-message {{ category }}">{{ message }}</div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}

  <h2>Active Jobs Postings</h2>
  <div class="job-cards">
    {% for job in jobs %}
    <div class="job-card">
      <h4>{{ job.job_title }}</h4>
      <p>
        <i class="fas fa-code"></i>
        Have Skills in <em class="line-clamp-2">{{ job.skills }}</em>
      </p>
      <p>
        <i class="fas fa-briefcase"></i>
        &nbsp;Min: {{ job.experience }} Years Experience
      </p>
      <div class="deadline-row">
        <p class="deadline">Available until: <span class="{% if job.is_expired %} text-expired {% endif %}">{{ job.deadline }}</span></p>
        <a href="{{ url_for('jobs.job_detail', job_id=job.id) }}" class="view-btn">View Detail</a>
      </div>
    </div>
    {% endfor %}
  </div>

  <script>
    setTimeout(() => {
      const flashMessages = document.querySelectorAll('.flash-message');
      flashMessages.forEach(msg => {
        msg.style.transition = 'opacity 0.5s ease';
        msg.style.opacity = '0';
        setTimeout(() => {
          msg.style.display = 'none';
        }, 500);
      });
    }, 5000);
  </script>
{% endblock %}

templates/dashboard_pelamar.jinja
{% extends "base_pelamar.jinja" %}

{% block title %}Dashboard - Pelamar{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard_pelamar.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
{% endblock %}

{% block content %}
  <h1>Recruitment Dashboard</h1>
  <p class='welcome-text'>Welcome Back, {{ user_name }}!</p>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <div class="flash-messages">
        {% for category, message in messages %}
          <div class="flash-message {{ category }}">{{ message }}</div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}

  <h2>Active Jobs Postings</h2>
  <div class="job-cards">
    {% for job in jobs %}
    <div class="job-card">
      <h4>{{ job.job_title }}</h4>
      <p>
        <i class="fas fa-code"></i>
        Have Skills in <em class="line-clamp-2">{{ job.skills }}</em>
      </p>
      <p>
        <i class="fas fa-briefcase"></i>
        &nbsp;Min: {{ job.experience }} Years Experience
      </p>
      <div class="deadline-row">
        <p class="deadline">Available until: <span>{{ job.deadline }}</span></p>
        <a href="{{ url_for('jobs.job_detail', job_id=job.id) }}" class="view-btn">View Detail</a>
      </div>
    </div>
    {% endfor %}
  </div>

  <script>
    setTimeout(() => {
      const flashMessages = document.querySelectorAll('.flash-message');
      flashMessages.forEach(msg => {
        msg.style.transition = 'opacity 0.5s ease';
        msg.style.opacity = '0';
        setTimeout(() => {
          msg.style.display = 'none';
        }, 500);
      });
    }, 3000);
  </script>
{% endblock %}

templates/signin.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign In</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/stylesl.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Segoe+UI:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>
<body>
    <div class="signup-box">
        <h2 style="color: yellow">Sign In</h2>

        {% if error %}
            <div class="error-message" id="error-message">{{ error }}</div>
        {% endif %}

        <form action="{{ url_for('auth.signin') }}" method="post">
            <input type="email" name="email" placeholder="Email" required>

            <div class="password-box">
                <input type="password" name="password" placeholder="Password" required />
                <span class="toggle-password" onclick="toggleVisibility(this)">
                    <i class="fa-solid fa-eye-slash active"></i>
                    <i class="fa-solid fa-eye"></i>
                </span>
            </div>

            <button type="submit">Sign In</button>
        </form>

        <p>Don't have an account? <a href="{{ url_for('auth.signup') }}">Sign Up</a></p>
    </div>

    <script>
        function toggleVisibility(el) {
            const input = el.previousElementSibling;
            const eyeSlash = el.querySelector('.fa-eye-slash');
            const eye = el.querySelector('.fa-eye');

            if (input.type === "password") {
                input.type = "text";
                eyeSlash.classList.remove("active");
                eye.classList.add("active");
            } else {
                input.type = "password";
                eye.classList.remove("active");
                eyeSlash.classList.add("active");
            }
        }

        const errorDiv = document.getElementById('error-message');
        if (errorDiv) {
            setTimeout(() => {
                errorDiv.style.display = 'none';
            }, 3000);
        }
    </script>
</body>
</html>